name: libexif
description: "Dart bindings for libexif."
version: 0.0.1

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: any

dev_dependencies:
  ffigen: any
  flutter_lints: ^3.0.0

ffigen:
  output: 'lib/libexif.dart'
  name: 'LibExif'
  description: 'Dart bindings to libexif'
  exclude-all-by-default: true
  functions:
    include:
      - exif_.*
      - mnote_.*
  structs:
    include:
      - _Exif.*
      - _?Mnote.*
  enums:
    include:
      - Exif.*
      - _?Mnote.*
      - Olympus.*
      - Pentax.*
  globals:
    include:
      - .*
  typedefs:
    include:
      - Exif.*
      - Mnote.*
      - va_list
  compiler-opts:
    - '-I.'
  headers:
    entry-points:
      - 'libexif/**.h'
